import type { CompendiumItem } from "./types";

/** Curated SRD gear: weapons, armor, adventuring kit, and a few magic items. */
export const COMPENDIUM_ITEMS: CompendiumItem[] = [
  // --- Weapons ---
  {
    name: "Dagger",
    category: "weapon",
    weight: 1,
    value: 2,
    damage: "1d4 piercing",
    properties: "Finesse, light, thrown (20/60)",
  },
  {
    name: "Shortsword",
    category: "weapon",
    weight: 2,
    value: 10,
    damage: "1d6 piercing",
    properties: "Finesse, light",
  },
  {
    name: "Longsword",
    category: "weapon",
    weight: 3,
    value: 15,
    damage: "1d8 slashing",
    properties: "Versatile (1d10)",
  },
  {
    name: "Rapier",
    category: "weapon",
    weight: 2,
    value: 25,
    damage: "1d8 piercing",
    properties: "Finesse",
  },
  {
    name: "Greatsword",
    category: "weapon",
    weight: 6,
    value: 50,
    damage: "2d6 slashing",
    properties: "Heavy, two-handed",
  },
  {
    name: "Greataxe",
    category: "weapon",
    weight: 7,
    value: 30,
    damage: "1d12 slashing",
    properties: "Heavy, two-handed",
  },
  {
    name: "Handaxe",
    category: "weapon",
    weight: 2,
    value: 5,
    damage: "1d6 slashing",
    properties: "Light, thrown (20/60)",
  },
  {
    name: "Warhammer",
    category: "weapon",
    weight: 2,
    value: 15,
    damage: "1d8 bludgeoning",
    properties: "Versatile (1d10)",
  },
  {
    name: "Mace",
    category: "weapon",
    weight: 4,
    value: 5,
    damage: "1d6 bludgeoning",
    properties: "—",
  },
  {
    name: "Quarterstaff",
    category: "weapon",
    weight: 4,
    value: 1,
    damage: "1d6 bludgeoning",
    properties: "Versatile (1d8)",
  },
  {
    name: "Spear",
    category: "weapon",
    weight: 3,
    value: 1,
    damage: "1d6 piercing",
    properties: "Thrown (20/60), versatile (1d8)",
  },
  {
    name: "Shortbow",
    category: "weapon",
    weight: 2,
    value: 25,
    damage: "1d6 piercing",
    properties: "Ammunition (80/320), two-handed",
  },
  {
    name: "Longbow",
    category: "weapon",
    weight: 2,
    value: 50,
    damage: "1d8 piercing",
    properties: "Ammunition (150/600), heavy, two-handed",
  },
  {
    name: "Light Crossbow",
    category: "weapon",
    weight: 5,
    value: 25,
    damage: "1d8 piercing",
    properties: "Ammunition (80/320), loading, two-handed",
  },
  // --- Armor & shields ---
  {
    name: "Leather Armor",
    category: "armor",
    weight: 10,
    value: 10,
    properties: "AC 11 + Dex modifier (light)",
  },
  {
    name: "Studded Leather",
    category: "armor",
    weight: 13,
    value: 45,
    properties: "AC 12 + Dex modifier (light)",
  },
  {
    name: "Chain Shirt",
    category: "armor",
    weight: 20,
    value: 50,
    properties: "AC 13 + Dex modifier (max 2) (medium)",
  },
  {
    name: "Scale Mail",
    category: "armor",
    weight: 45,
    value: 50,
    properties: "AC 14 + Dex modifier (max 2), Stealth disadvantage (medium)",
  },
  {
    name: "Chain Mail",
    category: "armor",
    weight: 55,
    value: 75,
    properties: "AC 16, Str 13, Stealth disadvantage (heavy)",
  },
  {
    name: "Plate Armor",
    category: "armor",
    rarity: "common",
    weight: 65,
    value: 1500,
    properties: "AC 18, Str 15, Stealth disadvantage (heavy)",
  },
  {
    name: "Shield",
    category: "shield",
    weight: 6,
    value: 10,
    properties: "+2 AC",
  },
  // --- Adventuring gear ---
  {
    name: "Backpack",
    category: "gear",
    weight: 5,
    value: 2,
    description: "Holds up to 30 pounds or 1 cubic foot of gear.",
  },
  {
    name: "Bedroll",
    category: "gear",
    weight: 7,
    value: 1,
    description: "A simple roll for sleeping in the wild.",
  },
  {
    name: "Rope, Hempen (50 ft.)",
    category: "gear",
    weight: 10,
    value: 1,
    description: "Has 2 hit points and can be burst with a DC 17 Strength check.",
  },
  {
    name: "Torch",
    category: "gear",
    weight: 1,
    value: 0.01,
    description: "Burns for 1 hour, casting bright light in a 20-foot radius.",
  },
  {
    name: "Tinderbox",
    category: "gear",
    weight: 1,
    value: 0.5,
    description: "Lights a torch as an action, or other fires in about a minute.",
  },
  {
    name: "Rations (1 day)",
    category: "consumable",
    weight: 2,
    value: 0.5,
    description: "Dry foods suitable for extended travel.",
  },
  {
    name: "Waterskin",
    category: "gear",
    weight: 5,
    value: 0.2,
    description: "Holds 4 pints of liquid when full.",
  },
  {
    name: "Thieves' Tools",
    category: "tool",
    weight: 1,
    value: 25,
    description:
      "Proficiency lets you add your bonus to Dexterity checks to disarm traps and pick locks.",
  },
  {
    name: "Holy Symbol",
    category: "gear",
    weight: 1,
    value: 5,
    description: "A spellcasting focus for clerics and paladins.",
  },
  {
    name: "Spellbook",
    category: "gear",
    weight: 3,
    value: 50,
    description: "A leather-bound tome of 100 blank vellum pages for a wizard's spells.",
  },
  // --- Magic items ---
  {
    name: "Potion of Healing",
    category: "consumable",
    rarity: "common",
    weight: 0.5,
    value: 50,
    description: "Regain 2d4 + 2 hit points when you drink this potion (an action).",
  },
  {
    name: "Longsword, +1",
    category: "magic",
    rarity: "uncommon",
    weight: 3,
    value: 1000,
    damage: "1d8+1 slashing",
    properties: "Versatile (1d10), +1 to attack and damage rolls",
    description: "A magic longsword granting a +1 bonus to attack and damage rolls.",
  },
  {
    name: "Bag of Holding",
    category: "magic",
    rarity: "uncommon",
    weight: 15,
    value: 4000,
    description:
      "An interdimensional space holding up to 500 pounds, never weighing more than 15 pounds.",
  },
  {
    name: "Cloak of Protection",
    category: "magic",
    rarity: "uncommon",
    weight: 1,
    value: 3500,
    properties: "+1 AC and saving throws (requires attunement)",
    description: "You gain a +1 bonus to AC and saving throws while wearing this cloak.",
  },
  {
    name: "Boots of Elvenkind",
    category: "magic",
    rarity: "uncommon",
    weight: 1,
    value: 2500,
    description:
      "Your steps make no sound; you have advantage on Stealth checks made to move silently.",
  },
];
