import type { CompendiumMonster } from "./types";

/** Classic low-to-mid CR SRD monsters, ready to drop into the bestiary. */
export const COMPENDIUM_MONSTERS: CompendiumMonster[] = [
  {
    name: "Goblin",
    size: "Small",
    type: "Humanoid (goblinoid)",
    alignment: "Neutral Evil",
    armorClass: 15,
    armorNote: "leather armor, shield",
    maxHp: 7,
    hitDiceFormula: "2d6",
    speed: "30 ft.",
    abilityScores: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    skills: "Stealth +6",
    senses: "Darkvision 60 ft., Passive Perception 9",
    languages: "Common, Goblin",
    challengeRating: "1/4",
    traits: [
      {
        name: "Nimble Escape",
        description: "Can take the Disengage or Hide action as a bonus action on each of its turns.",
      },
    ],
    actions: [
      {
        name: "Scimitar",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) slashing damage.",
      },
      {
        name: "Shortbow",
        description: "Ranged Weapon Attack: +4 to hit, range 80/320 ft. Hit: 5 (1d6 + 2) piercing damage.",
      },
    ],
  },
  {
    name: "Hobgoblin",
    size: "Medium",
    type: "Humanoid (goblinoid)",
    alignment: "Lawful Evil",
    armorClass: 18,
    armorNote: "chain mail, shield",
    maxHp: 11,
    hitDiceFormula: "2d8 + 2",
    speed: "30 ft.",
    abilityScores: { str: 13, dex: 12, con: 12, int: 10, wis: 10, cha: 9 },
    senses: "Darkvision 60 ft., Passive Perception 10",
    languages: "Common, Goblin",
    challengeRating: "1/2",
    traits: [
      {
        name: "Martial Advantage",
        description:
          "Once per turn, deals an extra 7 (2d6) damage to a creature it hits if an ally is within 5 feet of that creature.",
      },
    ],
    actions: [
      {
        name: "Longsword",
        description: "Melee Weapon Attack: +3 to hit, reach 5 ft. Hit: 5 (1d8 + 1) slashing damage.",
      },
    ],
  },
  {
    name: "Bugbear",
    size: "Medium",
    type: "Humanoid (goblinoid)",
    alignment: "Chaotic Evil",
    armorClass: 16,
    armorNote: "hide armor, shield",
    maxHp: 27,
    hitDiceFormula: "5d8 + 5",
    speed: "30 ft.",
    abilityScores: { str: 15, dex: 14, con: 13, int: 8, wis: 11, cha: 9 },
    skills: "Stealth +6, Survival +2",
    senses: "Darkvision 60 ft., Passive Perception 10",
    languages: "Common, Goblin",
    challengeRating: "1",
    traits: [
      {
        name: "Brute",
        description: "A melee weapon deals one extra die of damage when the bugbear hits with it (included below).",
      },
    ],
    actions: [
      {
        name: "Morningstar",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 11 (2d8 + 2) piercing damage.",
      },
    ],
  },
  {
    name: "Kobold",
    size: "Small",
    type: "Humanoid (kobold)",
    alignment: "Lawful Evil",
    armorClass: 12,
    maxHp: 5,
    hitDiceFormula: "2d6 - 2",
    speed: "30 ft.",
    abilityScores: { str: 7, dex: 15, con: 9, int: 8, wis: 7, cha: 8 },
    senses: "Darkvision 60 ft., Passive Perception 8",
    languages: "Common, Draconic",
    challengeRating: "1/8",
    traits: [
      {
        name: "Pack Tactics",
        description: "Advantage on an attack roll against a creature if at least one ally is within 5 feet of it.",
      },
      {
        name: "Sunlight Sensitivity",
        description: "Disadvantage on attacks and Perception checks relying on sight while in sunlight.",
      },
    ],
    actions: [
      {
        name: "Dagger",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 4 (1d4 + 2) piercing damage.",
      },
    ],
  },
  {
    name: "Orc",
    size: "Medium",
    type: "Humanoid (orc)",
    alignment: "Chaotic Evil",
    armorClass: 13,
    armorNote: "hide armor",
    maxHp: 15,
    hitDiceFormula: "2d8 + 6",
    speed: "30 ft.",
    abilityScores: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
    skills: "Intimidation +2",
    senses: "Darkvision 60 ft., Passive Perception 10",
    languages: "Common, Orc",
    challengeRating: "1/2",
    traits: [
      {
        name: "Aggressive",
        description: "As a bonus action, can move up to its speed toward a hostile creature it can see.",
      },
    ],
    actions: [
      {
        name: "Greataxe",
        description: "Melee Weapon Attack: +5 to hit, reach 5 ft. Hit: 9 (1d12 + 3) slashing damage.",
      },
    ],
  },
  {
    name: "Skeleton",
    size: "Medium",
    type: "Undead",
    alignment: "Lawful Evil",
    armorClass: 13,
    armorNote: "armor scraps",
    maxHp: 13,
    hitDiceFormula: "2d8 + 4",
    speed: "30 ft.",
    abilityScores: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    senses: "Darkvision 60 ft., Passive Perception 9",
    languages: "understands its creator's languages but can't speak",
    challengeRating: "1/4",
    damageImmunities: "poison",
    conditionImmunities: "exhaustion, poisoned",
    actions: [
      {
        name: "Shortsword",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) piercing damage.",
      },
      {
        name: "Shortbow",
        description: "Ranged Weapon Attack: +4 to hit, range 80/320 ft. Hit: 5 (1d6 + 2) piercing damage.",
      },
    ],
  },
  {
    name: "Zombie",
    size: "Medium",
    type: "Undead",
    alignment: "Neutral Evil",
    armorClass: 8,
    maxHp: 22,
    hitDiceFormula: "3d8 + 9",
    speed: "20 ft.",
    abilityScores: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    senses: "Darkvision 60 ft., Passive Perception 8",
    languages: "understands its creator's languages but can't speak",
    challengeRating: "1/4",
    damageImmunities: "poison",
    conditionImmunities: "poisoned",
    traits: [
      {
        name: "Undead Fortitude",
        description:
          "If damage reduces the zombie to 0 HP, it makes a Constitution save (DC 5 + damage) to drop to 1 HP instead, unless the damage is radiant or from a critical hit.",
      },
    ],
    actions: [
      {
        name: "Slam",
        description: "Melee Weapon Attack: +3 to hit, reach 5 ft. Hit: 4 (1d6 + 1) bludgeoning damage.",
      },
    ],
  },
  {
    name: "Wolf",
    size: "Medium",
    type: "Beast",
    alignment: "Unaligned",
    armorClass: 13,
    maxHp: 11,
    hitDiceFormula: "2d8 + 2",
    speed: "40 ft.",
    abilityScores: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    skills: "Perception +3, Stealth +4",
    senses: "Passive Perception 13",
    languages: "—",
    challengeRating: "1/4",
    traits: [
      {
        name: "Pack Tactics",
        description: "Advantage on an attack roll against a creature if at least one ally is within 5 feet of it.",
      },
    ],
    actions: [
      {
        name: "Bite",
        description:
          "Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 7 (2d4 + 2) piercing damage. Target must succeed on a DC 11 Strength save or be knocked prone.",
      },
    ],
  },
  {
    name: "Dire Wolf",
    size: "Large",
    type: "Beast",
    alignment: "Unaligned",
    armorClass: 14,
    maxHp: 37,
    hitDiceFormula: "5d10 + 10",
    speed: "50 ft.",
    abilityScores: { str: 17, dex: 15, con: 15, int: 3, wis: 12, cha: 7 },
    skills: "Perception +3, Stealth +4",
    senses: "Passive Perception 13",
    languages: "—",
    challengeRating: "1",
    traits: [
      {
        name: "Pack Tactics",
        description: "Advantage on an attack roll against a creature if at least one ally is within 5 feet of it.",
      },
    ],
    actions: [
      {
        name: "Bite",
        description:
          "Melee Weapon Attack: +5 to hit, reach 5 ft. Hit: 10 (2d6 + 3) piercing damage. Target must succeed on a DC 13 Strength save or be knocked prone.",
      },
    ],
  },
  {
    name: "Giant Spider",
    size: "Large",
    type: "Beast",
    alignment: "Unaligned",
    armorClass: 14,
    maxHp: 26,
    hitDiceFormula: "4d10 + 4",
    speed: "30 ft., climb 30 ft.",
    abilityScores: { str: 14, dex: 16, con: 12, int: 2, wis: 11, cha: 4 },
    skills: "Stealth +7",
    senses: "Blindsight 10 ft., Darkvision 60 ft., Passive Perception 10",
    languages: "—",
    challengeRating: "1",
    traits: [
      {
        name: "Spider Climb",
        description: "Can climb difficult surfaces, including upside down on ceilings, without an ability check.",
      },
      {
        name: "Web Sense",
        description: "While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.",
      },
    ],
    actions: [
      {
        name: "Bite",
        description:
          "Melee Weapon Attack: +5 to hit, reach 5 ft. Hit: 7 (1d8 + 3) piercing damage, and the target makes a DC 11 Constitution save, taking 9 (2d8) poison damage on a failure (half on success).",
      },
    ],
  },
  {
    name: "Bandit",
    size: "Medium",
    type: "Humanoid",
    alignment: "Any Non-Lawful",
    armorClass: 12,
    armorNote: "leather armor",
    maxHp: 11,
    hitDiceFormula: "2d8 + 2",
    speed: "30 ft.",
    abilityScores: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    senses: "Passive Perception 10",
    languages: "any one language (usually Common)",
    challengeRating: "1/8",
    actions: [
      {
        name: "Scimitar",
        description: "Melee Weapon Attack: +3 to hit, reach 5 ft. Hit: 4 (1d6 + 1) slashing damage.",
      },
      {
        name: "Light Crossbow",
        description: "Ranged Weapon Attack: +3 to hit, range 80/320 ft. Hit: 5 (1d8 + 1) piercing damage.",
      },
    ],
  },
  {
    name: "Bandit Captain",
    size: "Medium",
    type: "Humanoid",
    alignment: "Any Non-Lawful",
    armorClass: 15,
    armorNote: "studded leather",
    maxHp: 65,
    hitDiceFormula: "10d8 + 20",
    speed: "30 ft.",
    abilityScores: { str: 15, dex: 16, con: 14, int: 14, wis: 11, cha: 14 },
    savingThrows: "Str +4, Dex +5, Wis +2",
    skills: "Athletics +4, Deception +4",
    senses: "Passive Perception 10",
    languages: "any two languages",
    challengeRating: "2",
    actions: [
      {
        name: "Multiattack",
        description: "The captain makes three melee attacks: two with its scimitar and one with its dagger. Or it makes two ranged attacks with its daggers.",
      },
      {
        name: "Scimitar",
        description: "Melee Weapon Attack: +5 to hit, reach 5 ft. Hit: 6 (1d6 + 3) slashing damage.",
      },
    ],
  },
  {
    name: "Guard",
    size: "Medium",
    type: "Humanoid",
    alignment: "Any",
    armorClass: 16,
    armorNote: "chain shirt, shield",
    maxHp: 11,
    hitDiceFormula: "2d8 + 2",
    speed: "30 ft.",
    abilityScores: { str: 13, dex: 12, con: 12, int: 10, wis: 11, cha: 10 },
    skills: "Perception +2",
    senses: "Passive Perception 12",
    languages: "any one language (usually Common)",
    challengeRating: "1/8",
    actions: [
      {
        name: "Spear",
        description: "Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft. Hit: 4 (1d6 + 1) piercing damage.",
      },
    ],
  },
  {
    name: "Cultist",
    size: "Medium",
    type: "Humanoid",
    alignment: "Any Evil",
    armorClass: 12,
    armorNote: "leather armor",
    maxHp: 9,
    hitDiceFormula: "2d8",
    speed: "30 ft.",
    abilityScores: { str: 11, dex: 12, con: 10, int: 10, wis: 11, cha: 10 },
    skills: "Deception +2, Religion +2",
    senses: "Passive Perception 10",
    languages: "any one language (usually Common)",
    challengeRating: "1/8",
    actions: [
      {
        name: "Scimitar",
        description: "Melee Weapon Attack: +3 to hit, reach 5 ft. Hit: 4 (1d6 + 1) slashing damage.",
      },
    ],
  },
  {
    name: "Ogre",
    size: "Large",
    type: "Giant",
    alignment: "Chaotic Evil",
    armorClass: 11,
    armorNote: "hide armor",
    maxHp: 59,
    hitDiceFormula: "7d10 + 21",
    speed: "40 ft.",
    abilityScores: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    senses: "Darkvision 60 ft., Passive Perception 8",
    languages: "Common, Giant",
    challengeRating: "2",
    actions: [
      {
        name: "Greatclub",
        description: "Melee Weapon Attack: +6 to hit, reach 5 ft. Hit: 13 (2d8 + 4) bludgeoning damage.",
      },
    ],
  },
  {
    name: "Owlbear",
    size: "Large",
    type: "Monstrosity",
    alignment: "Unaligned",
    armorClass: 13,
    maxHp: 59,
    hitDiceFormula: "7d10 + 21",
    speed: "40 ft.",
    abilityScores: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    skills: "Perception +3",
    senses: "Darkvision 60 ft., Passive Perception 13",
    languages: "—",
    challengeRating: "3",
    traits: [
      {
        name: "Keen Sight and Smell",
        description: "Advantage on Perception checks that rely on sight or smell.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        description: "The owlbear makes two attacks: one with its beak and one with its claws.",
      },
      {
        name: "Claws",
        description: "Melee Weapon Attack: +7 to hit, reach 5 ft. Hit: 14 (2d8 + 5) slashing damage.",
      },
    ],
  },
  {
    name: "Ghoul",
    size: "Medium",
    type: "Undead",
    alignment: "Chaotic Evil",
    armorClass: 12,
    maxHp: 22,
    hitDiceFormula: "5d8",
    speed: "30 ft.",
    abilityScores: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    senses: "Darkvision 60 ft., Passive Perception 10",
    languages: "Common",
    challengeRating: "1",
    damageImmunities: "poison",
    conditionImmunities: "charmed, exhaustion, poisoned",
    actions: [
      {
        name: "Claws",
        description:
          "Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 7 (2d4 + 2) slashing damage. A non-elf target must succeed on a DC 10 Constitution save or be paralyzed for 1 minute (repeat save each turn).",
      },
    ],
  },
  {
    name: "Wight",
    size: "Medium",
    type: "Undead",
    alignment: "Neutral Evil",
    armorClass: 14,
    armorNote: "studded leather",
    maxHp: 45,
    hitDiceFormula: "6d8 + 18",
    speed: "30 ft.",
    abilityScores: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    skills: "Perception +3, Stealth +4",
    senses: "Darkvision 60 ft., Passive Perception 13",
    languages: "the languages it knew in life",
    challengeRating: "3",
    damageResistances: "necrotic; bludgeoning, piercing, and slashing from nonmagical attacks",
    conditionImmunities: "exhaustion, poisoned",
    traits: [
      {
        name: "Sunlight Sensitivity",
        description: "Disadvantage on attacks and Perception checks relying on sight while in sunlight.",
      },
    ],
    actions: [
      {
        name: "Life Drain",
        description:
          "Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) necrotic damage. Target makes a DC 13 Constitution save or its hit point maximum is reduced by the damage taken.",
      },
    ],
  },
  {
    name: "Gnoll",
    size: "Medium",
    type: "Humanoid (gnoll)",
    alignment: "Chaotic Evil",
    armorClass: 15,
    armorNote: "hide armor, shield",
    maxHp: 22,
    hitDiceFormula: "5d8",
    speed: "30 ft.",
    abilityScores: { str: 14, dex: 12, con: 11, int: 6, wis: 10, cha: 7 },
    senses: "Darkvision 60 ft., Passive Perception 10",
    languages: "Gnoll",
    challengeRating: "1/2",
    traits: [
      {
        name: "Rampage",
        description:
          "When it reduces a creature to 0 HP with a melee attack, the gnoll can take a bonus action to move up to half its speed and make a bite attack.",
      },
    ],
    actions: [
      {
        name: "Spear",
        description: "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft. Hit: 5 (1d6 + 2) piercing damage.",
      },
    ],
  },
  {
    name: "Animated Armor",
    size: "Medium",
    type: "Construct",
    alignment: "Unaligned",
    armorClass: 18,
    maxHp: 33,
    hitDiceFormula: "6d8 + 6",
    speed: "25 ft.",
    abilityScores: { str: 14, dex: 11, con: 13, int: 1, wis: 3, cha: 1 },
    senses: "Blindsight 60 ft. (blind beyond), Passive Perception 6",
    languages: "—",
    challengeRating: "1",
    damageImmunities: "poison, psychic",
    conditionImmunities: "blinded, charmed, deafened, exhaustion, frightened, paralyzed, petrified, poisoned",
    traits: [
      {
        name: "Antimagic Susceptibility",
        description: "Incapacitated while in an antimagic field; if targeted by dispel magic, must save or fall unconscious for 1 minute.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        description: "The armor makes two melee attacks.",
      },
      {
        name: "Slam",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) bludgeoning damage.",
      },
    ],
  },
];
