import type { CompendiumSpell } from "./types";

/** A curated SRD spell selection spanning cantrips through 5th level. */
export const COMPENDIUM_SPELLS: CompendiumSpell[] = [
  // --- Cantrips ---
  {
    name: "Fire Bolt",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Hurl a mote of fire at a creature or object. Make a ranged spell attack; on a hit it takes 1d10 fire damage. The damage increases at 5th (2d10), 11th (3d10), and 17th level (4d10).",
  },
  {
    name: "Ray of Frost",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "A frigid beam streaks toward a creature. Ranged spell attack; on a hit it takes 1d8 cold damage and its speed is reduced by 10 feet until your next turn.",
  },
  {
    name: "Shocking Grasp",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Lightning springs from your hand. Melee spell attack with advantage if the target wears metal armor; on a hit it takes 1d8 lightning damage and can't take reactions until its next turn.",
  },
  {
    name: "Eldritch Blast",
    level: 0,
    school: "Evocation",
    classes: ["Warlock"],
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "A beam of crackling energy. Ranged spell attack; on a hit the target takes 1d10 force damage. You create additional beams at 5th, 11th, and 17th level.",
  },
  {
    name: "Sacred Flame",
    level: 0,
    school: "Evocation",
    classes: ["Cleric"],
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Flame-like radiance descends on a creature. It must succeed on a Dexterity save or take 1d8 radiant damage. Ignores cover.",
  },
  {
    name: "Vicious Mockery",
    level: 0,
    school: "Enchantment",
    classes: ["Bard"],
    castingTime: "1 action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description:
      "A string of insults laced with enchantment. The target must succeed on a Wisdom save or take 1d4 psychic damage and have disadvantage on its next attack roll.",
  },
  {
    name: "Guidance",
    level: 0,
    school: "Divination",
    classes: ["Cleric", "Druid"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Up to 1 minute",
    concentration: true,
    description:
      "Touch a willing creature. Once before the spell ends, it can add 1d4 to one ability check of its choice.",
  },
  {
    name: "Mage Hand",
    level: 0,
    school: "Conjuration",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "1 action",
    range: "30 feet",
    components: "V, S",
    duration: "1 minute",
    description:
      "A spectral hand appears and can manipulate objects, open doors, or carry up to 10 pounds. It can't attack or activate magic items.",
  },
  {
    name: "Minor Illusion",
    level: 0,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "1 action",
    range: "30 feet",
    components: "S, M",
    duration: "1 minute",
    description:
      "Create a sound or an image of an object within range that lasts for the duration. Investigation check vs. your save DC to discern an illusion.",
  },
  {
    name: "Light",
    level: 0,
    school: "Evocation",
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, M",
    duration: "1 hour",
    description:
      "An object sheds bright light in a 20-foot radius and dim light for another 20 feet. A hostile creature can make a Dexterity save to avoid the spell.",
  },
  // --- 1st level ---
  {
    name: "Magic Missile",
    level: 1,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Three glowing darts each strike a target you can see for 1d4+1 force damage; they always hit. At higher levels, one extra dart per slot level above 1st.",
  },
  {
    name: "Cure Wounds",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "A creature you touch regains 1d8 + your spellcasting modifier hit points. +1d8 per slot level above 1st. No effect on undead or constructs.",
  },
  {
    name: "Healing Word",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Cleric", "Druid"],
    castingTime: "1 bonus action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description:
      "A creature you can see regains 1d4 + your spellcasting modifier hit points. +1d4 per slot level above 1st.",
  },
  {
    name: "Shield",
    level: 1,
    school: "Abjuration",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 reaction",
    range: "Self",
    components: "V, S",
    duration: "1 round",
    description:
      "An invisible barrier grants +5 AC until the start of your next turn, including against the triggering attack, and you take no damage from Magic Missile.",
  },
  {
    name: "Burning Hands",
    level: 1,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "Self (15-foot cone)",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Flames spread from your fingertips. Each creature in a 15-foot cone makes a Dexterity save, taking 3d6 fire damage (half on a success). +1d6 per slot above 1st.",
  },
  {
    name: "Thunderwave",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "Self (15-foot cube)",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "A wave of thunderous force. Each creature in a 15-foot cube makes a Constitution save, taking 2d8 thunder damage and being pushed 10 feet on a failure (half damage, no push on success).",
  },
  {
    name: "Bless",
    level: 1,
    school: "Enchantment",
    classes: ["Cleric", "Paladin"],
    castingTime: "1 action",
    range: "30 feet",
    components: "V, S, M",
    duration: "Up to 1 minute",
    concentration: true,
    description:
      "Up to three creatures add 1d4 to each attack roll and saving throw they make for the duration.",
  },
  {
    name: "Faerie Fire",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Druid"],
    castingTime: "1 action",
    range: "60 feet",
    components: "V",
    duration: "Up to 1 minute",
    concentration: true,
    description:
      "Objects and creatures in a 20-foot cube are outlined in light (Dexterity save negates). Attacks against them have advantage and they can't benefit from invisibility.",
  },
  {
    name: "Sleep",
    level: 1,
    school: "Enchantment",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "90 feet",
    components: "V, S, M",
    duration: "1 minute",
    description:
      "Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures with the lowest current HP are affected first and fall unconscious. +2d8 per slot above 1st.",
  },
  {
    name: "Hunter's Mark",
    level: 1,
    school: "Divination",
    classes: ["Ranger"],
    castingTime: "1 bonus action",
    range: "90 feet",
    components: "V",
    duration: "Up to 1 hour",
    concentration: true,
    description:
      "Mark a creature; you deal an extra 1d6 damage to it with weapon attacks and have advantage on Perception/Survival checks to find it.",
  },
  // --- 2nd level ---
  {
    name: "Misty Step",
    level: 2,
    school: "Conjuration",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "1 bonus action",
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    description:
      "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.",
  },
  {
    name: "Scorching Ray",
    level: 2,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Create three rays of fire. Make a ranged spell attack for each; a hit deals 2d6 fire damage. One extra ray per slot above 2nd.",
  },
  {
    name: "Hold Person",
    level: 2,
    school: "Enchantment",
    classes: ["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S, M",
    duration: "Up to 1 minute",
    concentration: true,
    description:
      "A humanoid must succeed on a Wisdom save or be paralyzed, repeating the save at the end of each of its turns. +1 target per slot above 2nd.",
  },
  {
    name: "Spiritual Weapon",
    level: 2,
    school: "Evocation",
    classes: ["Cleric"],
    castingTime: "1 bonus action",
    range: "60 feet",
    components: "V, S",
    duration: "1 minute",
    description:
      "Create a floating spectral weapon. As a bonus action you can move it and make a melee spell attack dealing 1d8 + your modifier force damage. +1d8 per two slots above 2nd.",
  },
  {
    name: "Invisibility",
    level: 2,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M",
    duration: "Up to 1 hour",
    concentration: true,
    description:
      "A creature you touch becomes invisible until it attacks or casts a spell. +1 target per slot above 2nd.",
  },
  {
    name: "Lesser Restoration",
    level: 2,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "End one disease or the blinded, deafened, paralyzed, or poisoned condition on a creature you touch.",
  },
  // --- 3rd level ---
  {
    name: "Fireball",
    level: 3,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "150 feet",
    components: "V, S, M",
    duration: "Instantaneous",
    description:
      "A bright streak blossoms into flame. Each creature in a 20-foot radius makes a Dexterity save, taking 8d6 fire damage (half on success). +1d6 per slot above 3rd.",
  },
  {
    name: "Counterspell",
    level: 3,
    school: "Abjuration",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "1 reaction",
    range: "60 feet",
    components: "S",
    duration: "Instantaneous",
    description:
      "Interrupt a creature casting a spell. A spell of 3rd level or lower fails; for higher levels, make an ability check (DC 10 + the spell's level).",
  },
  {
    name: "Lightning Bolt",
    level: 3,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "Self (100-foot line)",
    components: "V, S, M",
    duration: "Instantaneous",
    description:
      "A stroke of lightning in a 100-foot line. Each creature makes a Dexterity save, taking 8d6 lightning damage (half on success). +1d6 per slot above 3rd.",
  },
  {
    name: "Dispel Magic",
    level: 3,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "1 action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "End spells of 3rd level or lower on a target automatically; for higher spells, make an ability check (DC 10 + the spell's level).",
  },
  {
    name: "Revivify",
    level: 3,
    school: "Necromancy",
    classes: ["Cleric", "Paladin"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M",
    duration: "Instantaneous",
    description:
      "Touch a creature that has died within the last minute. It returns to life with 1 hit point. Doesn't restore missing body parts.",
  },
  {
    name: "Spirit Guardians",
    level: 3,
    school: "Conjuration",
    classes: ["Cleric"],
    castingTime: "1 action",
    range: "Self (15-foot radius)",
    components: "V, S, M",
    duration: "Up to 10 minutes",
    concentration: true,
    description:
      "Spectral guardians swirl around you. Hostile creatures in the area move at half speed and take 3d8 radiant or necrotic damage (Wisdom save halves). +1d8 per slot above 3rd.",
  },
  // --- 4th level ---
  {
    name: "Polymorph",
    level: 4,
    school: "Transmutation",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S, M",
    duration: "Up to 1 hour",
    concentration: true,
    description:
      "Transform a creature into a beast of equal or lower CR (Wisdom save negates for unwilling targets). It gains the beast's stats and temporary hit points.",
  },
  {
    name: "Greater Invisibility",
    level: 4,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S",
    duration: "Up to 1 minute",
    concentration: true,
    description:
      "A creature you touch is invisible for the duration, even while attacking and casting spells.",
  },
  {
    name: "Banishment",
    level: 4,
    school: "Abjuration",
    classes: ["Cleric", "Paladin", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S, M",
    duration: "Up to 1 minute",
    concentration: true,
    description:
      "A creature must succeed on a Charisma save or be banished to a harmless demiplane. Extraplanar creatures don't return. +1 target per slot above 4th.",
  },
  // --- 5th level ---
  {
    name: "Cone of Cold",
    level: 5,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "1 action",
    range: "Self (60-foot cone)",
    components: "V, S, M",
    duration: "Instantaneous",
    description:
      "A blast of cold air. Each creature in a 60-foot cone makes a Constitution save, taking 8d8 cold damage (half on success). +1d8 per slot above 5th.",
  },
  {
    name: "Greater Restoration",
    level: 5,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid"],
    castingTime: "1 action",
    range: "Touch",
    components: "V, S, M",
    duration: "Instantaneous",
    description:
      "Reduce a creature's exhaustion by one, or end a charm, petrification, a curse, or reduction to ability score or hit point maximum.",
  },
  {
    name: "Mass Cure Wounds",
    level: 5,
    school: "Evocation",
    classes: ["Bard", "Cleric", "Druid"],
    castingTime: "1 action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description:
      "Up to six creatures in a 30-foot radius each regain 3d8 + your spellcasting modifier hit points. +1d8 per slot above 5th.",
  },
  {
    name: "Hold Monster",
    level: 5,
    school: "Enchantment",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "1 action",
    range: "90 feet",
    components: "V, S, M",
    duration: "Up to 1 minute",
    concentration: true,
    description:
      "A creature must succeed on a Wisdom save or be paralyzed, repeating the save each turn. +1 target per slot above 5th.",
  },
];
